language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: VXBI4jsY1rW+s/3bgyWiPwsNsyZcZmUAr+CCoIixdjyCJdgWYRWroCpRilpmzwTrf1GtNY1D+y5S2mY6iMAA80VAD1nnM2R+Mm4XuagIaWKto1iWHRoweSshnrGcUSU7bPJkPfIPG+oTCLDM9V8kOdnBnEzxkdPT4mIcPGlVt4EcOmsSI+OBdySV8RjdOFWT4ddXnw6G+UmlrO9pkcPHzUEREgH4MWQEN3u5OaVHyGKbBf11eQrRDmfHGlsC/pBG7JfnWUHPwfcoutezQy9D8kibFVEMDURJl+gHQC0Vuo1OS2+ZbTYQbDV0z4G8nzzAg7hxLNDTnoxIoTveEjaTkJshRguGWlHw0kkq4XAAz8eYLaYe2O6NYMWw7DvRA7AdTbNs3w9Qqm5axfH+fKrQW2LxyTYQcNuv2xV1Q6E77LnFGQDcNJ6JBmqiyyF1H8CQggN7BJTB5ZhhsqXCyj6eC4sPjBoo9cFhpv1Ezh4zIep33QVNtYW/DyAGUt8k+LEP2CaoMkasOSqObmti5yF83JBPcaurKYIyGt2fN0sXnMisjzxjTWSr9/qsQxZBle4kkj6HWojTmfMaJSLMqPt4Vad8fan6UKQ7Xd7h5w32hEXwIP1Q2y6XfT/vV5/EE8sYpixcF0Oeo5HiwGMypScD9yFSQQQyNNsGoTmF8Jz3nYE=
