language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_deploy:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  app: graphql-nodejs
  api_key:
    secure: b32NJgDmmOxMZQqjv5rWMs0xlwiovDFSBiBXXLx+CeGAA0bAnpPpLmrqF2h3l4yVhMir08NqHR1RQfBmfXrrbnQgra/rY98wcyk4Tho4bDFlZjJwD2kc+uFP58LpTbH+EBrPYZfPEsRIP38Q3NiV65aMAI3u9PhIR18eTglDkkWeKEF6eCBdC7Cj6LUjLm8YoZ5tUGS1IRrj1aBjJkg1GZaX531bNGW49rL/xXo40OkzQWy3Sb5ZNSEpv7xekA7GcgJrC7eeESuPT/maNEeErHAwXdM0u2sZG5g5jLgZS0utrTkfyl5fq176AhAvZh7c1xyf2ZK3R6JiffiL/dnCShzb2Ad+Z88XBOxJpoUetULKBpH8JzrMBhcE9hVFo532wcY5SOuopcdSxtUnEWY1gb7QPqS6X8ld6UpgQ+xUS1n3agD5hwHTeD3rS/jVf15GYwh+KAB5duqpogpW9MYJYfZDUev8M7vf6YryiIKBTjY4Z3hWGd/jUfi19LxHRbkbji22b+9Y2J2xUHbXsN0jal9k7BWoJ/hK9gQJTsetoHje0ce34NVCM6bZ0Uw57A5UUudIr3ougzG3yEUUV3HUDNJZFtvk4O5QoP7SnV/p/m73v1IZlmSNVOazBlcJOJJe6nm+V8S+wrLeb19kcRi0w+rVLYGplwVAyLz5GjxJqWk=
